merchex/merchex/urls.py
from django.contrib import admin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.urls import path
from listings import views


def response_error_handler(request, exception=None):
    return HttpResponse('Error handler content', status=404)


def permission_denied_view(request):
    raise PermissionDenied


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='bands'),
    path('bands/add', views.band_create, name='band-create'),
    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    path('bands/<int:band_id>/change', views.band_change, name='band-change'),
    path('bands/<int:band_id>/delete', views.band_delete, name='band-delete'),
    path('about-us/', views.about, name='about'),
    path('listings/', views.listings, name='listings'),
    path('listings/add', views.listing_create, name='listing-create'),
    path('listings/<int:listing_id>/', views.listing_detail, name='listing-detail'),
    path('listings/<int:listing_id>/change', views.listing_change, name='listing-change'),
    path('listings/<int:listing_id>/delete', views.listing_delete, name='listing-delete'),
    path('contact-us/', views.contact, name='contact'),
    path('email-sent/', views.email_sent, name='email-sent'),
    path('404/', permission_denied_view),
]

handler404 = response_error_handler

merchex/listings/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        ROCK = 'ROCK'
        ALTERNATIVE = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2023)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class Listing(models.Model):
    class Type(models.TextChoices):
        DISQUES = 'Records'
        VETEMENTS = 'Clothing'
        POSTERS = 'Posters'
        DIVERS = 'Misc'

    title = models.fields.CharField(max_length=100)
    type = models.fields.CharField(choices=Type.choices, max_length=50)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(null=True, blank=True)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        # fields = '__all__'
        exclude = ('active', 'official_homepage')


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        exclude = ('sold', 'band')

merchex/listings/views.py
from datetime import datetime

from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from listings.models import Band, Listing
from listings.forms import ContactUsForm, BandForm, ListingForm


def band_list(request):
    bands = Band.objects.all()
    return render(
        request,
        'listings/band-list.html',
        {'bands': bands}
    )


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(
        request,
        'listings/band-create.html',
        {'form': form}
    )


def band_change(request, band_id):
    band = get_object_or_404(Band, id=band_id)
    if request.method == 'POST':
        form = BandForm(request.POST, band)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)
    return render(
        request,
        'listings/band-change.html',
        {
            'id': band_id,
            'form': form
        }
    )


def band_delete(request, band_id):
    band = get_object_or_404(Band, id=band_id)
    if request.method == 'POST':
        band.delete()
        messages.success(request, 'Groupe supprimé avec succès!')
        return redirect('bands')
    return render(
        request,
        'listings/band-delete.html',
        {
            'id': band_id,
            'band': band
        }
    )


def band_detail(request, band_id):
    # band = Band.objects.get(id=band_id)
    band = get_object_or_404(Band, id=band_id)
    return render(
        request,
        'listings/band-detail.html',
        {'band': band}
    )


def about(request):
    return render(request, 'listings/about.html')


def listings(request):
    listings_tab = Listing.objects.all()
    return render(
        request,
        'listings/listings.html',
        {'listings_tab': listings_tab}
    )


def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()
    return render(
        request,
        'listings/listing-create.html',
        {'form': form}
    )


def listing_change(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect('listing-detail', listing_id)
    else:
        form = ListingForm(instance=listing)
    return render(
        request,
        'listings/listing-change.html',
        {
            'id': listing_id,
            'form': form
        }
    )


def listing_delete(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id)
    if request.method == 'POST':
        listing.delete()
        messages.success(request, 'Annonce supprimée avec succès!')
        return redirect('listings')
    return render(
        request,
        'listings/listing-delete.html',
        {
            'id': listing_id,
            'listing': listing
        }
    )


def listing_detail(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id)
    return render(
        request,
        'listings/listing-detail.html',
        {'listing': listing}
    )


def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data.get("name") or "anonyme"} via Merchex Contact Us from',
                message=form.cleaned_data.get('message'),
                from_email=form.cleaned_data.get('email'),
                recipient_list=['admin@merchex.xyz'],
            )
            request.session['email'] = form.cleaned_data.get('email')
            return redirect('email-sent')
    else:
        form = ContactUsForm()
    return render(
        request,
        'listings/contact.html',
        {'form': form}
    )


def email_sent(request):
    email = request.session.pop('email', None)
    return render(
        request,
        'listings/email-sent.html',
        {'email': email}
    )

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block title %}À propos{% endblock %}

{% block content %}
<h1>À propos</h1>
<p>Nous adorons merch !</p>
{% endblock %}

merchex/listings/templates/listings/band-change.html
{% extends 'listings/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card w-50 mx-auto">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h2>Modification du groupe</h2>
        </div>

        <div class="card-body p-4">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <input class="btn btn-outline-success" type="submit" value="Soumettre">
                    <a class="btn btn-light" href="{% url 'bands' %}">
                        Annuler
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

merchex/listings/templates/listings/band-create.html
{% extends 'listings/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card w-50 mx-auto">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h2>Création d'un groupe</h2>
        </div>
        <div class="card-body p-4">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="mt-4">
                    <input class="btn btn-outline-success" type="submit" value="Soumettre">
                    <a class="btn btn-light" href="{% url 'bands' %}">
                        Annuler
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

merchex/listings/templates/listings/band-delete.html
{% extends 'listings/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card w-50 mx-auto">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h2>Supprimer le groupe</h2>
        </div>
        <div class="card-body p-4">
            <p>Etes-vous sur de vouloir supprimer le groupe : {{ band.name }} ?</p>
            <form action="" method="POST">
                {% csrf_token %}
                <input class="btn btn-outline-danger" type="submit" value="Supprimer ce groupe">
            </form>
        </div>
    </div>
</div>
{% endblock %}

merchex/listings/templates/listings/band-detail.html
{% extends 'listings/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card w-50 mx-auto">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h2>{{ band.name }}</h2>
        </div>
        <div class="card-body p-4">
            <ul>
                <li>Genre : {{ band.get_genre_display }}</li>
                <li>Année de formation : {{ band.year_formed }}</li>
                <li>Actif : {{ band.active|yesno }}</li>
                {% if band.official_homepage %}
                <li><a href="{{ band.official_homepage }}" target="_blank">{{ band.official_homepage }}</a></li>
                {% endif %}
            </ul>

            <p>{{ band.biography }}</p>

            {% if band.listing_set.all %}
            <h4>Liste des annonces liées au groupe :</h4>
            <ul>
                {% for listing in band.listing_set.all %}
                <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
                {% endfor %}
            </ul>
            {% endif %}
            <div class="mt-4">
                <a class="btn btn-primary" href="{% url 'band-change' band.id %}">
                    Modifier ce groupe
                </a>
                <a class="btn btn-outline-danger" href="{% url 'band-delete' band.id %}">
                    Supprimer ce groupe
                </a>
                <a class="btn btn-light" href="{% url 'bands' %}">
                    Retour
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

merchex/listings/templates/listings/band-list.html
{% extends 'listings/base.html' %}

{% block title %}Merchex{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card w-50 mx-auto">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h1>Groupes</h1>
            <a href="{% url 'band-create' %}">
                <button class="btn btn-outline-primary"><i class="fa-solid fa-plus"></i></button>
            </a>
        </div>

        <div class="card-body">
            <ul class="row gap-2">
                {% for band in bands %}
                <li>
                    <a href="{% url 'band-detail' band.id %}">{{band.name|upper}}</a>
                    -
                    <a class="me-2" href="{% url 'band-change' band.id %}"><i
                            class="fa-regular fa-pen-to-square"></i></a>
                    <a href="{% url 'band-delete' band.id %}"><i class="fa-solid fa-xmark text-danger"></i></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bands/style.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>

<nav class="navbar navbar-expand-lg bg-light shadow">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Merchex</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'bands' %}">Groupes</a>
                <a class="nav-link" href="{% url 'listings' %}">Annonces</a>
                <a class="nav-link" href="{% url 'about' %}">À propos</a>
                <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </div>
        </div>
    </div>
</nav>

{% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %} alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <strong class="alert-heading">{{ message }}</strong>
    </div>
    {% endfor %}
{% endif %}

{% block content %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://kit.fontawesome.com/9414e04596.js" crossorigin="anonymous"></script>

</body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card w-50 mx-auto">
        <div class="card-header d-flex flex-column">
            <h2>Contactez-nous</h2>
            <p>Nous sommes là pour vous aider !</p>
        </div>
        <div class="card-body p-4">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-outline-success mt-4" type="submit" value="Envoyer">
            </form>
        </div>
    </div>
</div>
{% endblock %}

merchex/listings/templates/listings/email-sent.html
{% extends 'listings/base.html' %}

{% block title %}Informations{% endblock %}

{% block content %}
<h2>Demande de contact</h2>

<p>
    Votre demande d'information a bien été envoyé !
    <br>
    Vous recevrez très prochainement un retour sur l'adresse : <br>
    {{ email }}
</p>
{% endblock %}

merchex/listings/templates/listings/listing-change.html
{% extends 'listings/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card w-50 mx-auto">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h2>Modification de l'annonce</h2>
        </div>
        <div class="card-body p-4">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <input class="btn btn-outline-success" type="submit" value="Soumettre">
                    <a class="btn btn-light" href="{% url 'listings' %}">
                        Annuler
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

merchex/listings/templates/listings/listing-create.html
{% extends 'listings/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card w-50 mx-auto">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h2>Création d'une annonce</h2>
        </div>
        <div class="card-body p-4">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="mt-4">
                    <input class="btn btn-outline-success" type="submit" value="Soumettre">
                    <a class="btn btn-light" href="{% url 'listings' %}">
                        Annuler
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

merchex/listings/templates/listings/listing-delete.html
{% extends 'listings/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card w-50 mx-auto">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h2>Supprimer une annonce</h2>
        </div>
        <div class="card-body p-4">
            <p>Etes-vous sur de vouloir supprimer cette annonce : {{ listing.title }} ?</p>
            <form action="" method="POST">
                {% csrf_token %}
                <input class="btn btn-outline-danger" type="submit" value="Supprimer cette annonce">
            </form>
        </div>
    </div>
</div>
{% endblock %}

merchex/listings/templates/listings/listing-detail.html
{% extends 'listings/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card w-50 mx-auto">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h2>{{ listing.title }}</h2>
        </div>
        <div class="card-body p-4">
            <ul>
                <li>type : {{ listing.get_type_display }}</li>
                <li>Vendu : {{ listing.sold|yesno }}</li>
                <li>Année de création : {{ listing.year }}</li>
                <li>Groupe lié : {{ listing.band }}</li>
            </ul>

            <p>{{ listing.description }}</p>
            <div>
                <a class="btn btn-primary" href="{% url 'listing-change' listing.id %}">
                    Modifier cette annonce
                </a>
                <a class="btn btn-outline-danger" href="{% url 'listing-delete' listing.id %}">
                    Supprimer cette annonce
                </a>
                <a class="btn btn-light" href="{% url 'listings' %}">
                    Retour
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block title %}Annonces{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card w-75 mx-auto">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h1>Listes des annonces</h1>
            <a href="{% url 'listing-create' %}">
                <button class="btn btn-outline-primary"><i class="fa-solid fa-plus"></i></button>
            </a>
        </div>
        <div class="card-body">
            <ul class="row gap-2">
                {% for item in listings_tab %}
                <li>
                    <a href="{% url 'listing-detail' item.id %}">{{item.title}}</a>
                    -
                    <a class="me-2" href="{% url 'listing-change' item.id %}"><i
                            class="fa-regular fa-pen-to-square"></i></a>
                    <a href="{% url 'listing-delete' item.id %}"><i class="fa-solid fa-xmark text-danger"></i></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}